### ISSUE TITLE
Gnome-Shell Menu Separators Doubled

### ISSUE THREAD

**Issue by JDNightwalker** [B00merang-Project/OS-X-Mavericks#3]
I am really loving this theme, but I've run into a small issue with the gnome-shell portion. The menu separators, both coming down from the panel or from the dock, are doubled. Also, there may be missing elements and icons. Attached is a view from the OS-X-Mavericks 1.1 version compared to a Materia Theme variant.

The problem can be duplicated in both the OS-X-Leopard 1.1 as well as OS-X-Yosemite 2.0.

Thanks!!

![Shell Menu Issue](https://user-images.githubusercontent.com/59395012/90969739-f68c7a80-e4b0-11ea-9259-1f22a2160356.png)

**Comment by JDNightwalker** [comment]
Tested using Ubuntu 20.04 with Gnome 3.36.3 on X11.

**Comment by Elbullazul** [comment]
will look into it

**Comment by Elbullazul** [comment]
fixed
