### ISSUE TITLE
Gnome-Shell Power Off Button Font Issue

### ISSUE THREAD

**Issue by JDNightwalker** [B00merang-Project/OS-X-Mavericks#4]
If you use a wider font as your system font, the "Power Off" button in the bottom right hand corner of the Power Off dialog in Gnome-Shell may appear as "Power..." instead of the full text, "Power Off".

This behavior can be duplicated in OS-X-Leopard 1.1 and OS-X-Yosemite 2.0.

Tested using Ubuntu 20.04 with Gnome 3.36.3 running on X11.

Thanks!!!

**Comment by Elbullazul** [comment]
does it happen with other themes as well?

**Comment by JDNightwalker** [comment]
I've managed to test the font (Lucida Grande) with the Adwaita, Materia and Yaru Gnome-Shell themes. The problem does not occur with those themes. The problem does also occur using OS-X-Mavericks and the Ubuntu Regular font. I also tested using the Ubuntu Condensed Regular font, at which point "Power Off" displayed normally. I think the problem may be with the width of the button and the space available for the text.

**Comment by Elbullazul** [comment]
can you share how Adwaita handles the situation?

**Comment by JDNightwalker** [comment]
I managed to grab a couple of screen shots to show you what I'm seeing. I'm not sure what's going on in the code, but it just feels like Gnome Shell is compensating under OS-X-Mavericks for too much text in too small a space by chopping it off and adding the ellipsis. Maybe the button could be made larger, some of the margin or cell buffer reduced, or the font made smaller / less bold in order to reduce its size?

Mavericks:
![Power Off Mavericks](https://user-images.githubusercontent.com/59395012/91089651-b6d8a680-e608-11ea-8f4e-bf8fd1fc855b.png)

Adwaita:
![Power Off Adwaita](https://user-images.githubusercontent.com/59395012/91089679-c3f59580-e608-11ea-95ee-4e1b114a68de.png)

**Comment by Elbullazul** [comment]
it's weird how it looks smaller in adwaita. I'll see what I can do

**Comment by Elbullazul** [comment]
0641d6d fixes this
