### ISSUE TITLE
Gnome-Shell List Jutification

### ISSUE THREAD

**Issue by JDNightwalker** [B00merang-Project/OS-X-Mavericks#5]
I just happened to notice that the justification of submenus in OS-X-Mavericks is a little off. Instead of the indentation matching the text of the menu element above like other shell themes, it indents to the left in an unnatural manner. Without having a genuine Macintosh running Mavericks in front of me, I'm thinking this may be a bug. Screenshots attached below.

Sorry for all the issues I keep finding! I just really like this theme!

OS-X-Mavericks:
![List Indent Mavericks](https://user-images.githubusercontent.com/59395012/91090982-c5c05880-e60a-11ea-8fec-ef8b71bc9b71.png)

Materia:
![List Indent Materia](https://user-images.githubusercontent.com/59395012/91091006-ceb12a00-e60a-11ea-81ad-39e49eea574d.png)

Adwaita:
![List Indent Adwaita](https://user-images.githubusercontent.com/59395012/91091023-d5d83800-e60a-11ea-93a1-32f2d4194ee1.png)

**Comment by Elbullazul** [comment]
![mavericks-wifi](https://cdn.osxdaily.com/wp-content/uploads/2011/06/extended-wifi-data.jpg)

you're right. It's not global indentation that's off, just the sub menu. Should be an easy fix.

> Sorry for all the issues I keep finding!

That's why we have a bug tracker! Glad you're enjoying the theme and helping improve it

**Comment by Elbullazul** [comment]
fixed
