### ISSUE TITLE
Icon theme?

### ISSUE THREAD

**Issue by linuxer0x42** [B00merang-Project/OS-X-Mavericks#6]
Where do I find the icon theme?

**Comment by Elbullazul** [comment]
If I remember correctly, it was [this one](https://launchpad.net/~noobslab/+archive/ubuntu/icons/+packages?field.name_filter=lion&field.status_filter=published&field.series_filter=), though it's probably broken by now

**Comment by linuxer0x42** [comment]
yeah I've found a newer icon theme alternative now

**Comment by Elbullazul** [comment]
would you mind sharing a link to that newer icon theme?

**Comment by linuxer0x42** [comment]
This one, I think it fits well with this theme: https://github.com/vinceliuice/McMojave-circle
@Elbullazul Sorry for responding so late btw
